// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIL8-ZV6i6FI9ND5gl0StEiaw8iQ6bcss',
    appId: '1:739915181729:android:40a02115b94f004ab7cae0',
    messagingSenderId: '739915181729',
    projectId: 'flutterauthtask',
    databaseURL: 'https://flutterauthtask-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterauthtask.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC85XnoCDWylFKcB8NMCP74bDyLhjH_a48',
    appId: '1:739915181729:ios:c86703434e1c0975b7cae0',
    messagingSenderId: '739915181729',
    projectId: 'flutterauthtask',
    databaseURL: 'https://flutterauthtask-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterauthtask.appspot.com',
    iosBundleId: 'com.example.flutterAuthTask',
  );
}
